// src/utils/dataGeografica.js

export const regiones = [
  { id: "15", nombre: "Arica y Parinacota" },
  { id: "01", nombre: "Tarapacá" },
  { id: "02", nombre: "Antofagasta" },
  { id: "03", nombre: "Atacama" },
  { id: "04", nombre: "Coquimbo" },
  { id: "05", nombre: "Valparaíso" },
  { id: "13", nombre: "Metropolitana de Santiago" },
  { id: "06", nombre: "Libertador General Bernardo O'Higgins" },
  { id: "07", nombre: "Maule" },
  { id: "16", nombre: "Ñuble" },
  { id: "08", nombre: "Biobío" },
  { id: "09", nombre: "La Araucanía" },
  { id: "14", nombre: "Los Ríos" },
  { id: "10", nombre: "Los Lagos" },
  { id: "11", nombre: "Aysén del General Carlos Ibáñez del Campo" },
  { id: "12", nombre: "Magallanes y de la Antártica Chilena" },
];

export const comunas = [
  // Región 15: Arica y Parinacota
  { id: 343, nombre: "Arica", regionId: "15" },
  { id: 344, nombre: "Camarones", regionId: "15" },
  { id: 345, nombre: "Putre", regionId: "15" },
  { id: 346, nombre: "General Lagos", regionId: "15" },

  // Región 01: Tarapacá
  { id: 1, nombre: "Iquique", regionId: "01" },
  { id: 2, nombre: "Alto Hospicio", regionId: "01" },
  { id: 3, nombre: "Pozo Almonte", regionId: "01" },
  { id: 4, nombre: "Camiña", regionId: "01" },
  { id: 5, nombre: "Colchane", regionId: "01" },
  { id: 6, nombre: "Huara", regionId: "01" },
  { id: 7, nombre: "Pica", regionId: "01" },

  // Región 02: Antofagasta
  { id: 8, nombre: "Antofagasta", regionId: "02" },
  { id: 9, nombre: "Mejillones", regionId: "02" },
  { id: 10, nombre: "Sierra Gorda", regionId: "02" },
  { id: 11, nombre: "Taltal", regionId: "02" },
  { id: 12, nombre: "Calama", regionId: "02" },
  { id: 13, nombre: "Ollagüe", regionId: "02" },
  { id: 14, nombre: "San Pedro de Atacama", regionId: "02" },
  { id: 15, nombre: "Tocopilla", regionId: "02" },
  { id: 16, nombre: "María Elena", regionId: "02" },

  // Región 03: Atacama
  { id: 17, nombre: "Copiapó", regionId: "03" },
  { id: 18, nombre: "Caldera", regionId: "03" },
  { id: 19, nombre: "Tierra Amarilla", regionId: "03" },
  { id: 20, nombre: "Chañaral", regionId: "03" },
  { id: 21, nombre: "Diego de Almagro", regionId: "03" },
  { id: 22, nombre: "Vallenar", regionId: "03" },
  { id: 23, nombre: "Alto del Carmen", regionId: "03" },
  { id: 24, nombre: "Freirina", regionId: "03" },
  { id: 25, nombre: "Huasco", regionId: "03" },

  // Región 04: Coquimbo
  { id: 26, nombre: "La Serena", regionId: "04" },
  { id: 27, nombre: "Coquimbo", regionId: "04" },
  { id: 28, nombre: "Andacollo", regionId: "04" },
  { id: 29, nombre: "La Higuera", regionId: "04" },
  { id: 30, nombre: "Paiguano", regionId: "04" },
  { id: 31, nombre: "Vicuña", regionId: "04" },
  { id: 32, nombre: "Illapel", regionId: "04" },
  { id: 33, nombre: "Canela", regionId: "04" },
  { id: 34, nombre: "Los Vilos", regionId: "04" },
  { id: 35, nombre: "Salamanca", regionId: "04" },
  { id: 36, nombre: "Ovalle", regionId: "04" },
  { id: 37, nombre: "Combarbalá", regionId: "04" },
  { id: 38, nombre: "Monte Patria", regionId: "04" },
  { id: 39, nombre: "Punitaqui", regionId: "04" },
  { id: 40, nombre: "Río Hurtado", regionId: "04" },

  // Región 05: Valparaíso
  { id: 41, nombre: "Valparaíso", regionId: "05" },
  { id: 42, nombre: "Casablanca", regionId: "05" },
  { id: 43, nombre: "Concón", regionId: "05" },
  { id: 44, nombre: "Juan Fernández", regionId: "05" },
  { id: 45, nombre: "Puchuncaví", regionId: "05" },
  { id: 46, nombre: "Quintero", regionId: "05" },
  { id: 47, nombre: "Viña del Mar", regionId: "05" },
  { id: 48, nombre: "Isla de Pascua", regionId: "05" },
  { id: 49, nombre: "Los Andes", regionId: "05" },
  { id: 50, nombre: "Calle Larga", regionId: "05" },
  { id: 51, nombre: "Rinconada", regionId: "05" },
  { id: 52, nombre: "San Esteban", regionId: "05" },
  { id: 53, nombre: "La Ligua", regionId: "05" },
  { id: 54, nombre: "Cabildo", regionId: "05" },
  { id: 55, nombre: "Papudo", regionId: "05" },
  { id: 56, nombre: "Petorca", regionId: "05" },
  { id: 57, nombre: "Zapallar", regionId: "05" },
  { id: 58, nombre: "Quillota", regionId: "05" },
  { id: 59, nombre: "Calera", regionId: "05" },
  { id: 60, nombre: "Hijuelas", regionId: "05" },
  { id: 61, nombre: "La Cruz", regionId: "05" },
  { id: 62, nombre: "Nogales", regionId: "05" },
  { id: 63, nombre: "San Antonio", regionId: "05" },
  { id: 64, nombre: "Algarrobo", regionId: "05" },
  { id: 65, nombre: "Cartagena", regionId: "05" },
  { id: 66, nombre: "El Quisco", regionId: "05" },
  { id: 67, nombre: "El Tabo", regionId: "05" },
  { id: 68, nombre: "Santo Domingo", regionId: "05" },
  { id: 69, nombre: "San Felipe", regionId: "05" },
  { id: 70, nombre: "Catemu", regionId: "05" },
  { id: 71, nombre: "Llaillay", regionId: "05" },
  { id: 72, nombre: "Panquehue", regionId: "05" },
  { id: 73, nombre: "Putaendo", regionId: "05" },
  { id: 74, nombre: "Santa María", regionId: "05" },
  { id: 75, nombre: "Quilpué", regionId: "05" },
  { id: 76, nombre: "Limache", regionId: "05" },
  { id: 77, nombre: "Olmué", regionId: "05" },
  { id: 78, nombre: "Villa Alemana", regionId: "05" },

  // Región 06: Libertador General Bernardo O'Higgins
  { id: 79, nombre: "Rancagua", regionId: "06" },
  { id: 80, nombre: "Codegua", regionId: "06" },
  { id: 81, nombre: "Coinco", regionId: "06" },
  { id: 82, nombre: "Coltauco", regionId: "06" },
  { id: 83, nombre: "Doñihue", regionId: "06" },
  { id: 84, nombre: "Graneros", regionId: "06" },
  { id: 85, nombre: "Las Cabras", regionId: "06" },
  { id: 86, nombre: "Machalí", regionId: "06" },
  { id: 87, nombre: "Malloa", regionId: "06" },
  { id: 88, nombre: "Mostazal", regionId: "06" },
  { id: 89, nombre: "Olivar", regionId: "06" },
  { id: 90, nombre: "Peumo", regionId: "06" },
  { id: 91, nombre: "Pichidegua", regionId: "06" },
  { id: 92, nombre: "Quinta de Tilcoco", regionId: "06" },
  { id: 93, nombre: "Rengo", regionId: "06" },
  { id: 94, nombre: "Requínoa", regionId: "06" },
  { id: 95, nombre: "San Vicente", regionId: "06" },
  { id: 96, nombre: "Pichilemu", regionId: "06" },
  { id: 97, nombre: "La Estrella", regionId: "06" },
  { id: 98, nombre: "Litueche", regionId: "06" },
  { id: 99, nombre: "Marchihue", regionId: "06" },
  { id: 100, nombre: "Navidad", regionId: "06" },
  { id: 101, nombre: "Paredones", regionId: "06" },
  { id: 102, nombre: "San Fernando", regionId: "06" },
  { id: 103, nombre: "Chépica", regionId: "06" },
  { id: 104, nombre: "Chimbarongo", regionId: "06" },
  { id: 105, nombre: "Lolol", regionId: "06" },
  { id: 106, nombre: "Nancagua", regionId: "06" },
  { id: 107, nombre: "Palmilla", regionId: "06" },
  { id: 108, nombre: "Peralillo", regionId: "06" },
  { id: 109, nombre: "Placilla", regionId: "06" },
  { id: 110, nombre: "Pumanque", regionId: "06" },
  { id: 111, nombre: "Santa Cruz", regionId: "06" },

  // Región 07: Maule
  { id: 112, nombre: "Talca", regionId: "07" },
  { id: 113, nombre: "Constitución", regionId: "07" },
  { id: 114, nombre: "Curepto", regionId: "07" },
  { id: 115, nombre: "Empedrado", regionId: "07" },
  { id: 116, nombre: "Maule", regionId: "07" },
  { id: 117, nombre: "Pelarco", regionId: "07" },
  { id: 118, nombre: "Pencahue", regionId: "07" },
  { id: 119, nombre: "Río Claro", regionId: "07" },
  { id: 120, nombre: "San Clemente", regionId: "07" },
  { id: 121, nombre: "San Rafael", regionId: "07" },
  { id: 122, nombre: "Cauquenes", regionId: "07" },
  { id: 123, nombre: "Chanco", regionId: "07" },
  { id: 124, nombre: "Pelluhue", regionId: "07" },
  { id: 125, nombre: "Curicó", regionId: "07" },
  { id: 126, nombre: "Hualañé", regionId: "07" },
  { id: 127, nombre: "Licantén", regionId: "07" },
  { id: 128, nombre: "Molina", regionId: "07" },
  { id: 129, nombre: "Rauco", regionId: "07" },
  { id: 130, nombre: "Romeral", regionId: "07" },
  { id: 131, nombre: "Sagrada Familia", regionId: "07" },
  { id: 132, nombre: "Teno", regionId: "07" },
  { id: 133, nombre: "Vichuquén", regionId: "07" },
  { id: 134, nombre: "Linares", regionId: "07" },
  { id: 135, nombre: "Colbún", regionId: "07" },
  { id: 136, nombre: "Longaví", regionId: "07" },
  { id: 137, nombre: "Parral", regionId: "07" },
  { id: 138, nombre: "Retiro", regionId: "07" },
  { id: 139, nombre: "San Javier", regionId: "07" },
  { id: 140, nombre: "Villa Alegre", regionId: "07" },
  { id: 141, nombre: "Yerbas Buenas", regionId: "07" },

  // Región 08: Biobío
  { id: 142, nombre: "Concepción", regionId: "08" },
  { id: 143, nombre: "Coronel", regionId: "08" },
  { id: 144, nombre: "Chiguayante", regionId: "08" },
  { id: 145, nombre: "Florida", regionId: "08" },
  { id: 146, nombre: "Hualqui", regionId: "08" },
  { id: 147, nombre: "Lota", regionId: "08" },
  { id: 148, nombre: "Penco", regionId: "08" },
  { id: 149, nombre: "San Pedro de la Paz", regionId: "08" },
  { id: 150, nombre: "Santa Juana", regionId: "08" },
  { id: 151, nombre: "Talcahuano", regionId: "08" },
  { id: 152, nombre: "Tomé", regionId: "08" },
  { id: 153, nombre: "Hualpén", regionId: "08" },
  { id: 154, nombre: "Lebu", regionId: "08" },
  { id: 155, nombre: "Arauco", regionId: "08" },
  { id: 156, nombre: "Cañete", regionId: "08" },
  { id: 157, nombre: "Contulmo", regionId: "08" },
  { id: 158, nombre: "Curanilahue", regionId: "08" },
  { id: 159, nombre: "Los Álamos", regionId: "08" },
  { id: 160, nombre: "Tirúa", regionId: "08" },
  { id: 161, nombre: "Los Ángeles", regionId: "08" },
  { id: 162, nombre: "Antuco", regionId: "08" },
  { id: 163, nombre: "Cabrero", regionId: "08" },
  { id: 164, nombre: "Laja", regionId: "08" },
  { id: 165, nombre: "Mulchén", regionId: "08" },
  { id: 166, nombre: "Nacimiento", regionId: "08" },
  { id: 167, nombre: "Negrete", regionId: "08" },
  { id: 168, nombre: "Quilaco", regionId: "08" },
  { id: 169, nombre: "Quilleco", regionId: "08" },
  { id: 170, nombre: "San Rosendo", regionId: "08" },
  { id: 171, nombre: "Santa Bárbara", regionId: "08" },
  { id: 172, nombre: "Tucapel", regionId: "08" },
  { id: 173, nombre: "Yumbel", regionId: "08" },
  { id: 174, nombre: "Alto Biobío", regionId: "08" },

  // Región 09: La Araucanía
  { id: 175, nombre: "Temuco", regionId: "09" },
  { id: 176, nombre: "Carahue", regionId: "09" },
  { id: 177, nombre: "Cunco", regionId: "09" },
  { id: 178, nombre: "Curarrehue", regionId: "09" },
  { id: 179, nombre: "Freire", regionId: "09" },
  { id: 180, nombre: "Galvarino", regionId: "09" },
  { id: 181, nombre: "Gorbea", regionId: "09" },
  { id: 182, nombre: "Lautaro", regionId: "09" },
  { id: 183, nombre: "Loncoche", regionId: "09" },
  { id: 184, nombre: "Melipeuco", regionId: "09" },
  { id: 185, nombre: "Nueva Imperial", regionId: "09" },
  { id: 186, nombre: "Padre Las Casas", regionId: "09" },
  { id: 187, nombre: "Perquenco", regionId: "09" },
  { id: 188, nombre: "Pitrufquén", regionId: "09" },
  { id: 189, nombre: "Pucón", regionId: "09" },
  { id: 190, nombre: "Saavedra", regionId: "09" },
  { id: 191, nombre: "Teodoro Schmidt", regionId: "09" },
  { id: 192, nombre: "Toltén", regionId: "09" },
  { id: 193, nombre: "Vilcún", regionId: "09" },
  { id: 194, nombre: "Villarrica", regionId: "09" },
  { id: 195, nombre: "Cholchol", regionId: "09" },
  { id: 196, nombre: "Angol", regionId: "09" },
  { id: 197, nombre: "Collipulli", regionId: "09" },
  { id: 198, nombre: "Curacautín", regionId: "09" },
  { id: 199, nombre: "Ercilla", regionId: "09" },
  { id: 200, nombre: "Lonquimay", regionId: "09" },
  { id: 201, nombre: "Los Sauces", regionId: "09" },
  { id: 202, nombre: "Lumaco", regionId: "09" },
  { id: 203, nombre: "Purén", regionId: "09" },
  { id: 204, nombre: "Renaico", regionId: "09" },
  { id: 205, nombre: "Traiguén", regionId: "09" },
  { id: 206, nombre: "Victoria", regionId: "09" },

  // Región 10: Los Lagos
  { id: 207, nombre: "Puerto Montt", regionId: "10" },
  { id: 208, nombre: "Calbuco", regionId: "10" },
  { id: 209, nombre: "Cochamó", regionId: "10" },
  { id: 210, nombre: "Fresia", regionId: "10" },
  { id: 211, nombre: "Frutillar", regionId: "10" },
  { id: 212, nombre: "Los Muermos", regionId: "10" },
  { id: 213, nombre: "Llanquihue", regionId: "10" },
  { id: 214, nombre: "Maullín", regionId: "10" },
  { id: 215, nombre: "Puerto Varas", regionId: "10" },
  { id: 216, nombre: "Castro", regionId: "10" },
  { id: 217, nombre: "Ancud", regionId: "10" },
  { id: 218, nombre: "Chonchi", regionId: "10" },
  { id: 219, nombre: "Curaco de Vélez", regionId: "10" },
  { id: 220, nombre: "Dalcahue", regionId: "10" },
  { id: 221, nombre: "Puqueldón", regionId: "10" },
  { id: 222, nombre: "Queilén", regionId: "10" },
  { id: 223, nombre: "Quellón", regionId: "10" },
  { id: 224, nombre: "Quemchi", regionId: "10" },
  { id: 225, nombre: "Quinchao", regionId: "10" },
  { id: 226, nombre: "Osorno", regionId: "10" },
  { id: 227, nombre: "Puerto Octay", regionId: "10" },
  { id: 228, nombre: "Purranque", regionId: "10" },
  { id: 229, nombre: "Puyehue", regionId: "10" },
  { id: 230, nombre: "Río Negro", regionId: "10" },
  { id: 231, nombre: "San Juan de la Costa", regionId: "10" },
  { id: 232, nombre: "San Pablo", regionId: "10" },
  { id: 233, nombre: "Chaitén", regionId: "10" },
  { id: 234, nombre: "Futaleufú", regionId: "10" },
  { id: 235, nombre: "Hualaihué", regionId: "10" },
  { id: 236, nombre: "Palena", regionId: "10" },

  // Región 11: Aysén
  { id: 237, nombre: "Coihaique", regionId: "11" },
  { id: 238, nombre: "Lago Verde", regionId: "11" },
  { id: 239, nombre: "Aisén", regionId: "11" },
  { id: 240, nombre: "Cisnes", regionId: "11" },
  { id: 241, nombre: "Guaitecas", regionId: "11" },
  { id: 242, nombre: "Cochrane", regionId: "11" },
  { id: 243, nombre: "O'Higgins", regionId: "11" },
  { id: 244, nombre: "Tortel", regionId: "11" },
  { id: 245, nombre: "Chile Chico", regionId: "11" },
  { id: 246, nombre: "Río Ibáñez", regionId: "11" },

  // Región 12: Magallanes
  { id: 247, nombre: "Punta Arenas", regionId: "12" },
  { id: 248, nombre: "Laguna Blanca", regionId: "12" },
  { id: 249, nombre: "Río Verde", regionId: "12" },
  { id: 250, nombre: "San Gregorio", regionId: "12" },
  { id: 251, nombre: "Cabo de Hornos", regionId: "12" },
  { id: 252, nombre: "Antártica", regionId: "12" },
  { id: 253, nombre: "Porvenir", regionId: "12" },
  { id: 254, nombre: "Primavera", regionId: "12" },
  { id: 255, nombre: "Timaukel", regionId: "12" },
  { id: 256, nombre: "Natales", regionId: "12" },
  { id: 257, nombre: "Torres del Paine", regionId: "12" },

  // Región 13: Metropolitana
  { id: 258, nombre: "Santiago", regionId: "13" },
  { id: 259, nombre: "Cerrillos", regionId: "13" },
  { id: 260, nombre: "Cerro Navia", regionId: "13" },
  { id: 261, nombre: "Conchalí", regionId: "13" },
  { id: 262, nombre: "El Bosque", regionId: "13" },
  { id: 263, nombre: "Estación Central", regionId: "13" },
  { id: 264, nombre: "Huechuraba", regionId: "13" },
  { id: 265, nombre: "Independencia", regionId: "13" },
  { id: 266, nombre: "La Cisterna", regionId: "13" },
  { id: 267, nombre: "La Florida", regionId: "13" },
  { id: 268, nombre: "La Granja", regionId: "13" },
  { id: 269, nombre: "La Pintana", regionId: "13" },
  { id: 270, nombre: "La Reina", regionId: "13" },
  { id: 271, nombre: "Las Condes", regionId: "13" },
  { id: 272, nombre: "Lo Barnechea", regionId: "13" },
  { id: 273, nombre: "Lo Espejo", regionId: "13" },
  { id: 274, nombre: "Lo Prado", regionId: "13" },
  { id: 275, nombre: "Macul", regionId: "13" },
  { id: 276, nombre: "Maipú", regionId: "13" },
  { id: 277, nombre: "Ñuñoa", regionId: "13" },
  { id: 278, nombre: "Pedro Aguirre Cerda", regionId: "13" },
  { id: 279, nombre: "Peñalolén", regionId: "13" },
  { id: 280, nombre: "Providencia", regionId: "13" },
  { id: 281, nombre: "Pudahuel", regionId: "13" },
  { id: 282, nombre: "Quilicura", regionId: "13" },
  { id: 283, nombre: "Quinta Normal", regionId: "13" },
  { id: 284, nombre: "Recoleta", regionId: "13" },
  { id: 285, nombre: "Renca", regionId: "13" },
  { id: 286, nombre: "San Joaquín", regionId: "13" },
  { id: 287, nombre: "San Miguel", regionId: "13" },
  { id: 288, nombre: "San Ramón", regionId: "13" },
  { id: 289, nombre: "Vitacura", regionId: "13" },
  { id: 290, nombre: "Puente Alto", regionId: "13" },
  { id: 291, nombre: "Pirque", regionId: "13" },
  { id: 292, nombre: "San José de Maipo", regionId: "13" },
  { id: 293, nombre: "Colina", regionId: "13" },
  { id: 294, nombre: "Lampa", regionId: "13" },
  { id: 295, nombre: "Tiltil", regionId: "13" },
  { id: 296, nombre: "San Bernardo", regionId: "13" },
  { id: 297, nombre: "Buin", regionId: "13" },
  { id: 298, nombre: "Calera de Tango", regionId: "13" },
  { id: 299, nombre: "Paine", regionId: "13" },
  { id: 300, nombre: "Melipilla", regionId: "13" },
  { id: 301, nombre: "Alhué", regionId: "13" },
  { id: 302, nombre: "Curacaví", regionId: "13" },
  { id: 303, nombre: "María Pinto", regionId: "13" },
  { id: 304, nombre: "San Pedro", regionId: "13" },
  { id: 305, nombre: "Talagante", regionId: "13" },
  { id: 306, nombre: "El Monte", regionId: "13" },
  { id: 307, nombre: "Isla de Maipo", regionId: "13" },
  { id: 308, nombre: "Padre Hurtado", regionId: "13" },
  { id: 309, nombre: "Peñaflor", regionId: "13" },

  // Región 14: Los Ríos
  { id: 310, nombre: "Valdivia", regionId: "14" },
  { id: 311, nombre: "Corral", regionId: "14" },
  { id: 312, nombre: "Futrono", regionId: "14" },
  { id: 313, nombre: "La Unión", regionId: "14" },
  { id: 314, nombre: "Lago Ranco", regionId: "14" },
  { id: 315, nombre: "Lanco", regionId: "14" },
  { id: 316, nombre: "Los Lagos", regionId: "14" },
  { id: 317, nombre: "Máfil", regionId: "14" },
  { id: 318, nombre: "Mariquina", regionId: "14" },
  { id: 319, nombre: "Paillaco", regionId: "14" },
  { id: 320, nombre: "Panguipulli", regionId: "14" },
  { id: 321, nombre: "Río Bueno", regionId: "14" },

  // Región 16: Ñuble
  { id: 322, nombre: "Chillán", regionId: "16" },
  { id: 323, nombre: "Bulnes", regionId: "16" },
  { id: 324, nombre: "Cobquecura", regionId: "16" },
  { id: 325, nombre: "Coelemu", regionId: "16" },
  { id: 326, nombre: "Coihueco", regionId: "16" },
  { id: 327, nombre: "Chillán Viejo", regionId: "16" },
  { id: 328, nombre: "El Carmen", regionId: "16" },
  { id: 329, nombre: "Ninhue", regionId: "16" },
  { id: 330, nombre: "Ñiquén", regionId: "16" },
  { id: 331, nombre: "Pemuco", regionId: "16" },
  { id: 332, nombre: "Pinto", regionId: "16" },
  { id: 333, nombre: "Portezuelo", regionId: "16" },
  { id: 334, nombre: "Quillón", regionId: "16" },
  { id: 335, nombre: "Quirihue", regionId: "16" },
  { id: 336, nombre: "Ránquil", regionId: "16" },
  { id: 337, nombre: "San Carlos", regionId: "16" },
  { id: 338, nombre: "San Fabián", regionId: "16" },
  { id: 339, nombre: "San Ignacio", regionId: "16" },
  { id: 340, nombre: "San Nicolás", regionId: "16" },
  { id: 341, nombre: "Treguaco", regionId: "16" },
  { id: 342, nombre: "Yungay", regionId: "16" },
];