// src/utils/dataGeografica.js

export const regiones = [
  { id: "15", nombre: "Arica y Parinacota" },
  { id: "01", nombre: "Tarapacá" },
  { id: "02", nombre: "Antofagasta" },
  { id: "03", nombre: "Atacama" },
  { id: "04", nombre: "Coquimbo" },
  { id: "05", nombre: "Valparaíso" },
  { id: "13", nombre: "Metropolitana de Santiago" },
  { id: "06", nombre: "Libertador General Bernardo O'Higgins" },
  { id: "07", nombre: "Maule" },
  { id: "16", nombre: "Ñuble" },
  { id: "08", nombre: "Biobío" },
  { id: "09", nombre: "La Araucanía" },
  { id: "14", nombre: "Los Ríos" },
  { id: "10", nombre: "Los Lagos" },
  { id: "11", nombre: "Aysén del General Carlos Ibáñez del Campo" },
  { id: "12", nombre: "Magallanes y de la Antártica Chilena" },
];

export const comunas = [
  // Región 15: Arica y Parinacota
  { nombre: "Arica", regionId: "15" },
  { nombre: "Camarones", regionId: "15" },
  { nombre: "Putre", regionId: "15" },
  { nombre: "General Lagos", regionId: "15" },

  // Región 01: Tarapacá
  { nombre: "Iquique", regionId: "01" },
  { nombre: "Alto Hospicio", regionId: "01" },
  { nombre: "Pozo Almonte", regionId: "01" },
  { nombre: "Camiña", regionId: "01" },
  { nombre: "Colchane", regionId: "01" },
  { nombre: "Huara", regionId: "01" },
  { nombre: "Pica", regionId: "01" },

  // Región 02: Antofagasta
  { nombre: "Antofagasta", regionId: "02" },
  { nombre: "Mejillones", regionId: "02" },
  { nombre: "Sierra Gorda", regionId: "02" },
  { nombre: "Taltal", regionId: "02" },
  { nombre: "Calama", regionId: "02" },
  { nombre: "Ollagüe", regionId: "02" },
  { nombre: "San Pedro de Atacama", regionId: "02" },
  { nombre: "Tocopilla", regionId: "02" },
  { nombre: "María Elena", regionId: "02" },

  // Región 03: Atacama
  { nombre: "Copiapó", regionId: "03" },
  { nombre: "Caldera", regionId: "03" },
  { nombre: "Tierra Amarilla", regionId: "03" },
  { nombre: "Chañaral", regionId: "03" },
  { nombre: "Diego de Almagro", regionId: "03" },
  { nombre: "Vallenar", regionId: "03" },
  { nombre: "Alto del Carmen", regionId: "03" },
  { nombre: "Freirina", regionId: "03" },
  { nombre: "Huasco", regionId: "03" },

  // Región 04: Coquimbo
  { nombre: "La Serena", regionId: "04" },
  { nombre: "Coquimbo", regionId: "04" },
  { nombre: "Andacollo", regionId: "04" },
  { nombre: "La Higuera", regionId: "04" },
  { nombre: "Paiguano", regionId: "04" },
  { nombre: "Vicuña", regionId: "04" },
  { nombre: "Illapel", regionId: "04" },
  { nombre: "Canela", regionId: "04" },
  { nombre: "Los Vilos", regionId: "04" },
  { nombre: "Salamanca", regionId: "04" },
  { nombre: "Ovalle", regionId: "04" },
  { nombre: "Combarbalá", regionId: "04" },
  { nombre: "Monte Patria", regionId: "04" },
  { nombre: "Punitaqui", regionId: "04" },
  { nombre: "Río Hurtado", regionId: "04" },

  // Región 05: Valparaíso
  { nombre: "Valparaíso", regionId: "05" },
  { nombre: "Casablanca", regionId: "05" },
  { nombre: "Concón", regionId: "05" },
  { nombre: "Juan Fernández", regionId: "05" },
  { nombre: "Puchuncaví", regionId: "05" },
  { nombre: "Quintero", regionId: "05" },
  { nombre: "Viña del Mar", regionId: "05" },
  { nombre: "Isla de Pascua", regionId: "05" },
  { nombre: "Los Andes", regionId: "05" },
  { nombre: "Calle Larga", regionId: "05" },
  { nombre: "Rinconada", regionId: "05" },
  { nombre: "San Esteban", regionId: "05" },
  { nombre: "La Ligua", regionId: "05" },
  { nombre: "Cabildo", regionId: "05" },
  { nombre: "Papudo", regionId: "05" },
  { nombre: "Petorca", regionId: "05" },
  { nombre: "Zapallar", regionId: "05" },
  { nombre: "Quillota", regionId: "05" },
  { nombre: "Calera", regionId: "05" },
  { nombre: "Hijuelas", regionId: "05" },
  { nombre: "La Cruz", regionId: "05" },
  { nombre: "Nogales", regionId: "05" },
  { nombre: "San Antonio", regionId: "05" },
  { nombre: "Algarrobo", regionId: "05" },
  { nombre: "Cartagena", regionId: "05" },
  { nombre: "El Quisco", regionId: "05" },
  { nombre: "El Tabo", regionId: "05" },
  { nombre: "Santo Domingo", regionId: "05" },
  { nombre: "San Felipe", regionId: "05" },
  { nombre: "Catemu", regionId: "05" },
  { nombre: "Llaillay", regionId: "05" },
  { nombre: "Panquehue", regionId: "05" },
  { nombre: "Putaendo", regionId: "05" },
  { nombre: "Santa María", regionId: "05" },
  { nombre: "Quilpué", regionId: "05" },
  { nombre: "Limache", regionId: "05" },
  { nombre: "Olmué", regionId: "05" },
  { nombre: "Villa Alemana", regionId: "05" },

  // Región 06: Libertador General Bernardo O'Higgins
  { nombre: "Rancagua", regionId: "06" },
  { nombre: "Codegua", regionId: "06" },
  { nombre: "Coinco", regionId: "06" },
  { nombre: "Coltauco", regionId: "06" },
  { nombre: "Doñihue", regionId: "06" },
  { nombre: "Graneros", regionId: "06" },
  { nombre: "Las Cabras", regionId: "06" },
  { nombre: "Machalí", regionId: "06" },
  { nombre: "Malloa", regionId: "06" },
  { nombre: "Mostazal", regionId: "06" },
  { nombre: "Olivar", regionId: "06" },
  { nombre: "Peumo", regionId: "06" },
  { nombre: "Pichidegua", regionId: "06" },
  { nombre: "Quinta de Tilcoco", regionId: "06" },
  { nombre: "Rengo", regionId: "06" },
  { nombre: "Requínoa", regionId: "06" },
  { nombre: "San Vicente", regionId: "06" },
  { nombre: "Pichilemu", regionId: "06" },
  { nombre: "La Estrella", regionId: "06" },
  { nombre: "Litueche", regionId: "06" },
  { nombre: "Marchihue", regionId: "06" },
  { nombre: "Navidad", regionId: "06" },
  { nombre: "Paredones", regionId: "06" },
  { nombre: "San Fernando", regionId: "06" },
  { nombre: "Chépica", regionId: "06" },
  { nombre: "Chimbarongo", regionId: "06" },
  { nombre: "Lolol", regionId: "06" },
  { nombre: "Nancagua", regionId: "06" },
  { nombre: "Palmilla", regionId: "06" },
  { nombre: "Peralillo", regionId: "06" },
  { nombre: "Placilla", regionId: "06" },
  { nombre: "Pumanque", regionId: "06" },
  { nombre: "Santa Cruz", regionId: "06" },

  // Región 07: Maule
  { nombre: "Talca", regionId: "07" },
  { nombre: "Constitución", regionId: "07" },
  { nombre: "Curepto", regionId: "07" },
  { nombre: "Empedrado", regionId: "07" },
  { nombre: "Maule", regionId: "07" },
  { nombre: "Pelarco", regionId: "07" },
  { nombre: "Pencahue", regionId: "07" },
  { nombre: "Río Claro", regionId: "07" },
  { nombre: "San Clemente", regionId: "07" },
  { nombre: "San Rafael", regionId: "07" },
  { nombre: "Cauquenes", regionId: "07" },
  { nombre: "Chanco", regionId: "07" },
  { nombre: "Pelluhue", regionId: "07" },
  { nombre: "Curicó", regionId: "07" },
  { nombre: "Hualañé", regionId: "07" },
  { nombre: "Licantén", regionId: "07" },
  { nombre: "Molina", regionId: "07" },
  { nombre: "Rauco", regionId: "07" },
  { nombre: "Romeral", regionId: "07" },
  { nombre: "Sagrada Familia", regionId: "07" },
  { nombre: "Teno", regionId: "07" },
  { nombre: "Vichuquén", regionId: "07" },
  { nombre: "Linares", regionId: "07" },
  { nombre: "Colbún", regionId: "07" },
  { nombre: "Longaví", regionId: "07" },
  { nombre: "Parral", regionId: "07" },
  { nombre: "Retiro", regionId: "07" },
  { nombre: "San Javier", regionId: "07" },
  { nombre: "Villa Alegre", regionId: "07" },
  { nombre: "Yerbas Buenas", regionId: "07" },

  // Región 08: Biobío
  { nombre: "Concepción", regionId: "08" },
  { nombre: "Coronel", regionId: "08" },
  { nombre: "Chiguayante", regionId: "08" },
  { nombre: "Florida", regionId: "08" },
  { nombre: "Hualqui", regionId: "08" },
  { nombre: "Lota", regionId: "08" },
  { nombre: "Penco", regionId: "08" },
  { nombre: "San Pedro de la Paz", regionId: "08" },
  { nombre: "Santa Juana", regionId: "08" },
  { nombre: "Talcahuano", regionId: "08" },
  { nombre: "Tomé", regionId: "08" },
  { nombre: "Hualpén", regionId: "08" },
  { nombre: "Lebu", regionId: "08" },
  { nombre: "Arauco", regionId: "08" },
  { nombre: "Cañete", regionId: "08" },
  { nombre: "Contulmo", regionId: "08" },
  { nombre: "Curanilahue", regionId: "08" },
  { nombre: "Los Álamos", regionId: "08" },
  { nombre: "Tirúa", regionId: "08" },
  { nombre: "Los Ángeles", regionId: "08" },
  { nombre: "Antuco", regionId: "08" },
  { nombre: "Cabrero", regionId: "08" },
  { nombre: "Laja", regionId: "08" },
  { nombre: "Mulchén", regionId: "08" },
  { nombre: "Nacimiento", regionId: "08" },
  { nombre: "Negrete", regionId: "08" },
  { nombre: "Quilaco", regionId: "08" },
  { nombre: "Quilleco", regionId: "08" },
  { nombre: "San Rosendo", regionId: "08" },
  { nombre: "Santa Bárbara", regionId: "08" },
  { nombre: "Tucapel", regionId: "08" },
  { nombre: "Yumbel", regionId: "08" },
  { nombre: "Alto Biobío", regionId: "08" },

  // Región 09: La Araucanía
  { nombre: "Temuco", regionId: "09" },
  { nombre: "Carahue", regionId: "09" },
  { nombre: "Cunco", regionId: "09" },
  { nombre: "Curarrehue", regionId: "09" },
  { nombre: "Freire", regionId: "09" },
  { nombre: "Galvarino", regionId: "09" },
  { nombre: "Gorbea", regionId: "09" },
  { nombre: "Lautaro", regionId: "09" },
  { nombre: "Loncoche", regionId: "09" },
  { nombre: "Melipeuco", regionId: "09" },
  { nombre: "Nueva Imperial", regionId: "09" },
  { nombre: "Padre Las Casas", regionId: "09" },
  { nombre: "Perquenco", regionId: "09" },
  { nombre: "Pitrufquén", regionId: "09" },
  { nombre: "Pucón", regionId: "09" },
  { nombre: "Saavedra", regionId: "09" },
  { nombre: "Teodoro Schmidt", regionId: "09" },
  { nombre: "Toltén", regionId: "09" },
  { nombre: "Vilcún", regionId: "09" },
  { nombre: "Villarrica", regionId: "09" },
  { nombre: "Cholchol", regionId: "09" },
  { nombre: "Angol", regionId: "09" },
  { nombre: "Collipulli", regionId: "09" },
  { nombre: "Curacautín", regionId: "09" },
  { nombre: "Ercilla", regionId: "09" },
  { nombre: "Lonquimay", regionId: "09" },
  { nombre: "Los Sauces", regionId: "09" },
  { nombre: "Lumaco", regionId: "09" },
  { nombre: "Purén", regionId: "09" },
  { nombre: "Renaico", regionId: "09" },
  { nombre: "Traiguén", regionId: "09" },
  { nombre: "Victoria", regionId: "09" },

  // Región 10: Los Lagos
  { nombre: "Puerto Montt", regionId: "10" },
  { nombre: "Calbuco", regionId: "10" },
  { nombre: "Cochamó", regionId: "10" },
  { nombre: "Fresia", regionId: "10" },
  { nombre: "Frutillar", regionId: "10" },
  { nombre: "Los Muermos", regionId: "10" },
  { nombre: "Llanquihue", regionId: "10" },
  { nombre: "Maullín", regionId: "10" },
  { nombre: "Puerto Varas", regionId: "10" },
  { nombre: "Castro", regionId: "10" },
  { nombre: "Ancud", regionId: "10" },
  { nombre: "Chonchi", regionId: "10" },
  { nombre: "Curaco de Vélez", regionId: "10" },
  { nombre: "Dalcahue", regionId: "10" },
  { nombre: "Puqueldón", regionId: "10" },
  { nombre: "Queilén", regionId: "10" },
  { nombre: "Quellón", regionId: "10" },
  { nombre: "Quemchi", regionId: "10" },
  { nombre: "Quinchao", regionId: "10" },
  { nombre: "Osorno", regionId: "10" },
  { nombre: "Puerto Octay", regionId: "10" },
  { nombre: "Purranque", regionId: "10" },
  { nombre: "Puyehue", regionId: "10" },
  { nombre: "Río Negro", regionId: "10" },
  { nombre: "San Juan de la Costa", regionId: "10" },
  { nombre: "San Pablo", regionId: "10" },
  { nombre: "Chaitén", regionId: "10" },
  { nombre: "Futaleufú", regionId: "10" },
  { nombre: "Hualaihué", regionId: "10" },
  { nombre: "Palena", regionId: "10" },

  // Región 11: Aysén
  { nombre: "Coihaique", regionId: "11" },
  { nombre: "Lago Verde", regionId: "11" },
  { nombre: "Aisén", regionId: "11" },
  { nombre: "Cisnes", regionId: "11" },
  { nombre: "Guaitecas", regionId: "11" },
  { nombre: "Cochrane", regionId: "11" },
  { nombre: "O'Higgins", regionId: "11" },
  { nombre: "Tortel", regionId: "11" },
  { nombre: "Chile Chico", regionId: "11" },
  { nombre: "Río Ibáñez", regionId: "11" },

  // Región 12: Magallanes
  { nombre: "Punta Arenas", regionId: "12" },
  { nombre: "Laguna Blanca", regionId: "12" },
  { nombre: "Río Verde", regionId: "12" },
  { nombre: "San Gregorio", regionId: "12" },
  { nombre: "Cabo de Hornos", regionId: "12" },
  { nombre: "Antártica", regionId: "12" },
  { nombre: "Porvenir", regionId: "12" },
  { nombre: "Primavera", regionId: "12" },
  { nombre: "Timaukel", regionId: "12" },
  { nombre: "Natales", regionId: "12" },
  { nombre: "Torres del Paine", regionId: "12" },

  // Región 13: Metropolitana
  { nombre: "Santiago", regionId: "13" },
  { nombre: "Cerrillos", regionId: "13" },
  { nombre: "Cerro Navia", regionId: "13" },
  { nombre: "Conchalí", regionId: "13" },
  { nombre: "El Bosque", regionId: "13" },
  { nombre: "Estación Central", regionId: "13" },
  { nombre: "Huechuraba", regionId: "13" },
  { nombre: "Independencia", regionId: "13" },
  { nombre: "La Cisterna", regionId: "13" },
  { nombre: "La Florida", regionId: "13" },
  { nombre: "La Granja", regionId: "13" },
  { nombre: "La Pintana", regionId: "13" },
  { nombre: "La Reina", regionId: "13" },
  { nombre: "Las Condes", regionId: "13" },
  { nombre: "Lo Barnechea", regionId: "13" },
  { nombre: "Lo Espejo", regionId: "13" },
  { nombre: "Lo Prado", regionId: "13" },
  { nombre: "Macul", regionId: "13" },
  { nombre: "Maipú", regionId: "13" },
  { nombre: "Ñuñoa", regionId: "13" },
  { nombre: "Pedro Aguirre Cerda", regionId: "13" },
  { nombre: "Peñalolén", regionId: "13" },
  { nombre: "Providencia", regionId: "13" },
  { nombre: "Pudahuel", regionId: "13" },
  { nombre: "Quilicura", regionId: "13" },
  { nombre: "Quinta Normal", regionId: "13" },
  { nombre: "Recoleta", regionId: "13" },
  { nombre: "Renca", regionId: "13" },
  { nombre: "San Joaquín", regionId: "13" },
  { nombre: "San Miguel", regionId: "13" },
  { nombre: "San Ramón", regionId: "13" },
  { nombre: "Vitacura", regionId: "13" },
  { nombre: "Puente Alto", regionId: "13" },
  { nombre: "Pirque", regionId: "13" },
  { nombre: "San José de Maipo", regionId: "13" },
  { nombre: "Colina", regionId: "13" },
  { nombre: "Lampa", regionId: "13" },
  { nombre: "Tiltil", regionId: "13" },
  { nombre: "San Bernardo", regionId: "13" },
  { nombre: "Buin", regionId: "13" },
  { nombre: "Calera de Tango", regionId: "13" },
  { nombre: "Paine", regionId: "13" },
  { nombre: "Melipilla", regionId: "13" },
  { nombre: "Alhué", regionId: "13" },
  { nombre: "Curacaví", regionId: "13" },
  { nombre: "María Pinto", regionId: "13" },
  { nombre: "San Pedro", regionId: "13" },
  { nombre: "Talagante", regionId: "13" },
  { nombre: "El Monte", regionId: "13" },
  { nombre: "Isla de Maipo", regionId: "13" },
  { nombre: "Padre Hurtado", regionId: "13" },
  { nombre: "Peñaflor", regionId: "13" },

  // Región 14: Los Ríos
  { nombre: "Valdivia", regionId: "14" },
  { nombre: "Corral", regionId: "14" },
  { nombre: "Futrono", regionId: "14" },
  { nombre: "La Unión", regionId: "14" },
  { nombre: "Lago Ranco", regionId: "14" },
  { nombre: "Lanco", regionId: "14" },
  { nombre: "Los Lagos", regionId: "14" },
  { nombre: "Máfil", regionId: "14" },
  { nombre: "Mariquina", regionId: "14" },
  { nombre: "Paillaco", regionId: "14" },
  { nombre: "Panguipulli", regionId: "14" },
  { nombre: "Río Bueno", regionId: "14" },

  // Región 16: Ñuble
  { nombre: "Chillán", regionId: "16" },
  { nombre: "Bulnes", regionId: "16" },
  { nombre: "Cobquecura", regionId: "16" },
  { nombre: "Coelemu", regionId: "16" },
  { nombre: "Coihueco", regionId: "16" },
  { nombre: "Chillán Viejo", regionId: "16" },
  { nombre: "El Carmen", regionId: "16" },
  { nombre: "Ninhue", regionId: "16" },
  { nombre: "Ñiquén", regionId: "16" },
  { nombre: "Pemuco", regionId: "16" },
  { nombre: "Pinto", regionId: "16" },
  { nombre: "Portezuelo", regionId: "16" },
  { nombre: "Quillón", regionId: "16" },
  { nombre: "Quirihue", regionId: "16" },
  { nombre: "Ránquil", regionId: "16" },
  { nombre: "San Carlos", regionId: "16" },
  { nombre: "San Fabián", regionId: "16" },
  { nombre: "San Ignacio", regionId: "16" },
  { nombre: "San Nicolás", regionId: "16" },
  { nombre: "Treguaco", regionId: "16" },
  { nombre: "Yungay", regionId: "16" },
];